# Site settings
title: Durango Shade Company Online Store
email: mschmidty@gmail.com
description: This is the original build for Marlins site. 
baseurl: "" # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: [
  .git,
  .gitignore,
  .DS_store,
  CNAME,
  svg,
  src,
  scss,
  .sass-cache,
  package.json,
  gulpfile.js,
  node_modules,
  readme.md,
  main.css
]
